[package]
name = "gencam_server"
version = "0.0.0"
authors = ["Sunip Mukherjee <sunipkmukherjee@gmail.com>, Mit Bailey <mitbailey@outlook.com>"]
edition = "2021"

[dependencies]
tungstenite = { version = "0.23.0" }